api = "0.2"

[buildpack]
  id = "com.anynines.buildpacks.rvm-bundler"
  name = "RVM Buildpack for Bundler"
  version = "0.0.1"

[metadata]
  include_files = ["bin/build","bin/detect","buildpack.toml"]

  [metadata.configuration]
    default_bundler_version = "2.1.4"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "heroku-18"
